import { expect, type Locator, type Page } from "@playwright/test";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { selectSettingsCategory } from "./settings-steps.ts";

export async function checkModuleSettings(page: Page, settings: Locator, configDirectory: string, artifact: string) {
	await selectSettingsCategory(page, "子代理");
	const dimensions = () => settings.evaluate((node) => ({ width: node.clientWidth, height: node.clientHeight }));
	const original = await dimensions();
	const parallel = settings.getByRole("spinbutton", { name: "最大并行任务数", exact: true });
	await expect(parallel).toHaveValue("4");
	await expect(settings.getByText(/继承默认|全局覆盖|后端电脑|不代表项目最终生效值/)).toHaveCount(0);
	const reset = settings.getByRole("button", { name: "重置最大并行任务数", exact: true });
	await expect(reset).toHaveText("");
	await expect(reset.locator("svg")).toHaveCount(1);
	await expect(reset).toBeDisabled();
	await parallel.fill("6");
	await expect(reset).toBeEnabled();
	for (const label of ["网络与网页", "权限与安全", "代码智能", "集成", "终端界面", "自动标题", "文件工具", "终端工具", "默认工具", "子代理"]) {
		await selectSettingsCategory(page, label);
		await expect(settings.getByRole("button", { name: "编辑 JSONC", exact: true })).toBeVisible();
		expect(await dimensions()).toEqual(original);
	}
	await expect(parallel).toHaveValue("6");
	await settings.getByRole("button", { name: "关闭面板", exact: true }).click();
	await expect(page.getByRole("dialog", { name: "放弃未保存的设置？" })).toBeVisible();
	await page.getByRole("button", { name: "继续编辑", exact: true }).click();
	await settings.getByRole("button", { name: "保存", exact: true }).click();
	const file = path.join(configDirectory, "subagent.jsonc");
	await expect.poll(async () => JSON.parse(await readFile(file, "utf8")).max_parallel_tasks).toBe(6);
	await expect(settings.getByText("已保存", { exact: true })).toBeVisible();
	await settings.getByRole("button", { name: "重置最大并行任务数", exact: true }).click();
	await expect(parallel).toHaveValue("4");
	await settings.getByRole("button", { name: "保存", exact: true }).click();
	await expect.poll(async () => JSON.parse(await readFile(file, "utf8")).max_parallel_tasks).toBeUndefined();
	await settings.getByRole("button", { name: "编辑 JSONC", exact: true }).click();
	const source = settings.getByRole("textbox", { name: "subagent 全局 JSONC", exact: true });
	await source.fill('{\n // 我的并发设置\n "max_parallel_tasks": 5,\n}\n');
	await settings.getByRole("button", { name: "保存", exact: true }).click();
	await expect(settings.getByRole("button", { name: "保存", exact: true })).toBeDisabled();
	await settings.getByRole("button", { name: "返回表单", exact: true }).click();
	await parallel.fill("7");
	await settings.getByRole("button", { name: "保存", exact: true }).click();
	await expect.poll(async () => await readFile(file, "utf8")).toContain("我的并发设置");
	await expect(settings.getByRole("button", { name: "保存", exact: true })).toBeDisabled();
	await writeFile(file, '{"max_parallel_tasks":3}');
	await parallel.fill("8");
	await settings.getByRole("button", { name: "保存", exact: true }).click();
	await expect(settings.getByRole("alert")).toContainText("保存失败");
	expect(JSON.parse(await readFile(file, "utf8")).max_parallel_tasks).toBe(3);
	await settings.getByRole("button", { name: "放弃修改", exact: true }).click();
	await settings.getByRole("button", { name: "重新读取", exact: true }).click();
	await expect(parallel).toHaveValue("3");
	await selectSettingsCategory(page, "自动标题");
	const model = settings.getByRole("textbox", { name: "标题模型（留空使用当前模型）", exact: true });
	await model.fill("test/model");
	await model.fill("");
	await settings.getByRole("button", { name: "保存", exact: true }).click();
	await expect.poll(async () => JSON.parse(await readFile(path.join(configDirectory, "auto-title.jsonc"), "utf8")).model).toBeNull();
	await selectSettingsCategory(page, "网络与网页");
	const proxy = settings.getByRole("checkbox", { name: "启用代理", exact: true });
	await expect(proxy).not.toBeChecked();
	const proxyBox = await proxy.boundingBox();
	expect(proxyBox).not.toBeNull();
	if (proxyBox) expect(proxyBox.width).toBeLessThan(proxyBox.height * 2);
	await proxy.check();
	await settings.getByRole("button", { name: "保存", exact: true }).click();
	await expect.poll(async () => JSON.parse(await readFile(path.join(configDirectory, "web-tools.jsonc"), "utf8")).network.proxy.enabled).toBe(true);
	await settings.getByRole("button", { name: "重置启用代理", exact: true }).click();
	await settings.getByRole("button", { name: "保存", exact: true }).click();
	await expect(proxy).not.toBeChecked();
	await expect(settings.getByRole("button", { name: "保存", exact: true })).toBeDisabled();
	await page.screenshot({ path: `dist/gui-settings-modules-${artifact}.png`, animations: "disabled" });
	await selectSettingsCategory(page, "外观");
}
