import { test, expect } from "./fixture.ts";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "jsonc-parser";
import { selectSetting, selectSettingsCategory } from "./settings-steps.ts";

for (const mode of ["web", "desktop"] as const) test.describe(mode, () => {
	test.use({ mode });
	test("偏好持久化、模块草稿和保存冲突", async ({ gui: { page }, workspace: { agentDir } }) => {
		const open = async () => {
			if ((page.viewportSize()?.width ?? 1200) < 768) await page.getByRole("button", { name: "菜单", exact: true }).click();
			await page.getByRole("button", { name: "设置", exact: true }).click();
		};
		const settings = page.getByRole("dialog", { name: "设置", exact: true });
		const file = path.join(agentDir, "configs", "gui.jsonc");
		const stored = async (): Promise<unknown> => parse(await readFile(file, "utf8"));
		await open();
		await selectSetting(page, "主题", "深色");
		await expect(async () => expect(await stored()).toMatchObject({ theme: "dark" })).toPass();
		await selectSettingsCategory(page, "交互");
		await selectSetting(page, "发送快捷键", "Enter（Shift + Enter 换行）");
		await expect(async () => expect(await stored()).toMatchObject({ sendShortcut: "enter" })).toPass();
		await selectSettingsCategory(page, "桌面 Web 访问");
		const enabled = settings.getByRole("checkbox", { name: "启用 Web 访问", exact: true });
		await expect(enabled).not.toBeChecked();
		const host = settings.getByRole("textbox", { name: "监听地址", exact: true });
		const port = settings.getByRole("spinbutton", { name: "监听端口", exact: true });
		await expect(host).toHaveValue("127.0.0.1");
		await expect(port).toHaveValue("19199");
		await host.fill("::1");
		await host.press("Enter");
		await expect(async () => expect(await stored()).toMatchObject({ desktopWeb: { host: "::1" } })).toPass();
		await port.fill("19200");
		await port.press("Enter");
		await expect(async () => expect(await stored()).toMatchObject({ desktopWeb: { port: 19200 } })).toPass({ timeout: 5000 });
		await enabled.click();
		await expect(enabled).toBeChecked();
		await expect(async () => expect(await stored()).toMatchObject({ desktopWeb: { enabled: true, host: "::1", port: 19200 } })).toPass();
		await expect(settings).toContainText("保存后需重启 Desktop");
		await page.reload();
		const editor = page.getByRole("textbox", { name: "消息", exact: true });
		await editor.fill("/name 快捷键验证");
		await editor.press("Enter");
		await expect(page.locator(".topbar .session-name")).toHaveText("快捷键验证");
		await open();
		await selectSettingsCategory(page, "子代理");
		const parallel = settings.getByRole("spinbutton", { name: "最大并行任务数", exact: true });
		await parallel.fill("6");
		await selectSettingsCategory(page, "自动标题");
		await selectSettingsCategory(page, "子代理");
		await expect(parallel).toHaveValue("6");
		await settings.getByRole("button", { name: "关闭面板", exact: true }).click();
		await page.getByRole("button", { name: "继续编辑", exact: true }).click();
		await settings.getByRole("button", { name: "保存", exact: true }).click();
		const moduleFile = path.join(agentDir, "configs", "subagent.jsonc");
		await expect(async () => expect(parse(await readFile(moduleFile, "utf8"))).toMatchObject({ max_parallel_tasks: 6 })).toPass();
		await expect(settings.getByRole("button", { name: "保存", exact: true })).toBeDisabled();
		await writeFile(moduleFile, '{"max_parallel_tasks":3}');
		await parallel.fill("8");
		await settings.getByRole("button", { name: "保存", exact: true }).click();
		await expect(settings.getByRole("alert")).toContainText("保存失败");
		await expect(parallel).toHaveValue("8");
		expect(parse(await readFile(moduleFile, "utf8"))).toEqual({ max_parallel_tasks: 3 });
		await settings.getByRole("button", { name: "放弃修改", exact: true }).click();
	});
});
