import { test, expect } from "./fixture.ts";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "jsonc-parser";
import { selectSetting, selectSettingsCategory } from "./settings-steps.ts";

test("分类草稿、关闭确认、保存与刷新恢复", async ({ gui: { page }, workspace: { agentDir } }) => {
	const open = async () => {
		if ((page.viewportSize()?.width ?? 1200) < 768) await page.getByRole("button", { name: "菜单", exact: true }).click();
		await page.getByRole("button", { name: "设置", exact: true }).click();
	};
	const settings = page.getByRole("dialog", { name: "设置", exact: true });
	const file = path.join(agentDir, "configs", "gui.jsonc");
	const stored = async (): Promise<unknown> => parse(await readFile(file, "utf8"));
	await writeFile(file, "{}\n");
	await open();
	const save = settings.getByRole("button", { name: "保存", exact: true });
	await expect(save).toBeDisabled();
	await selectSetting(page, "主题", "深色");
	await selectSettingsCategory(page, "交互");
	await selectSetting(page, "发送快捷键", "Enter（Shift + Enter 换行）");
	expect(await stored()).toEqual({});
	await save.click();
	await expect(async () => expect(await stored()).toEqual({ sendShortcut: "enter" })).toPass();
	await selectSettingsCategory(page, "外观");
	await settings.getByRole("button", { name: "关闭面板", exact: true }).click();
	await page.getByRole("button", { name: "继续编辑", exact: true }).click();
	await save.click();
	await expect(async () => expect(await stored()).toMatchObject({ theme: "dark", sendShortcut: "enter" })).toPass();
	await selectSetting(page, "主题", "浅色");
	await settings.getByRole("button", { name: "放弃修改", exact: true }).click();
	await expect(save).toBeDisabled();
	await selectSettingsCategory(page, "桌面 Web 访问");
	await settings.getByRole("textbox", { name: "监听地址", exact: true }).fill("::1");
	await settings.getByRole("spinbutton", { name: "监听端口", exact: true }).fill("19200");
	await settings.getByRole("checkbox", { name: "启用 Web 访问", exact: true }).check();
	expect(await stored()).not.toHaveProperty("desktopWeb");
	await save.click();
	await expect(async () => expect(await stored()).toMatchObject({ desktopWeb: { enabled: true, host: "::1", port: 19200 } })).toPass();
	await selectSettingsCategory(page, "子代理");
	const parallel = settings.getByRole("spinbutton", { name: "最大并行任务数", exact: true });
	await parallel.fill("6");
	await selectSettingsCategory(page, "自动标题");
	await selectSettingsCategory(page, "子代理");
	await expect(parallel).toHaveValue("6");
	await save.click();
	await expect(save).toBeDisabled();
	await settings.getByRole("button", { name: "关闭面板", exact: true }).click();
	await page.reload();
	await expect(page.locator("html")).toHaveAttribute("data-theme", "dark");
	const editor = page.getByRole("textbox", { name: "消息", exact: true });
	await editor.fill("/name 快捷键验证");
	await editor.press("Enter");
	await expect(page.locator(".topbar .session-name")).toHaveText("快捷键验证");
});
