import { test, expect } from "./fixture.ts";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "jsonc-parser";
import { selectSetting, selectSettingsCategory } from "./settings-steps.ts";

for (const mode of ["web", "desktop"] as const) test.describe(mode, () => {
	test.use({ mode });
	test("偏好持久化、模块草稿和保存冲突", async ({ gui: { page }, workspace: { agentDir } }) => {
		const open = async () => {
			if ((page.viewportSize()?.width ?? 1200) < 768) await page.getByRole("button", { name: "菜单", exact: true }).click();
			await page.getByRole("button", { name: "设置", exact: true }).click();
		};
		const settings = page.getByRole("dialog", { name: "设置", exact: true });
		const file = path.join(agentDir, "configs", "gui.jsonc");
		const stored = async (): Promise<unknown> => parse(await readFile(file, "utf8"));
		await writeFile(file, "{}\n");
		await open();
		const save = settings.getByRole("button", { name: "保存", exact: true });
		const discard = settings.getByRole("button", { name: "放弃修改", exact: true });
		await expect(save).toBeDisabled();
		await selectSetting(page, "主题", "深色");
		expect(await stored()).toEqual({});
		await selectSettingsCategory(page, "交互");
		await selectSetting(page, "发送快捷键", "Enter（Shift + Enter 换行）");
		expect(await stored()).toEqual({});
		await save.click();
		await expect(async () => expect(await stored()).toEqual({ sendShortcut: "enter" })).toPass();
		await selectSettingsCategory(page, "外观");
		await settings.getByRole("button", { name: "关闭面板", exact: true }).click();
		await page.getByRole("button", { name: "继续编辑", exact: true }).click();
		await save.click();
		await expect(async () => expect(await stored()).toMatchObject({ theme: "dark", sendShortcut: "enter" })).toPass();
		await selectSetting(page, "主题", "浅色");
		await discard.click();
		await expect(save).toBeDisabled();
		await selectSettingsCategory(page, "桌面 Web 访问");
		const enabled = settings.getByRole("checkbox", { name: "启用 Web 访问", exact: true });
		await expect(enabled).not.toBeChecked();
		const host = settings.getByRole("textbox", { name: "监听地址", exact: true });
		const port = settings.getByRole("spinbutton", { name: "监听端口", exact: true });
		await expect(host).toHaveValue("127.0.0.1");
		await host.fill("::1");
		await host.press("Enter");
		expect(await stored()).not.toHaveProperty("desktopWeb");
		await port.fill("19200");
		await port.press("Enter");
		expect(await stored()).not.toHaveProperty("desktopWeb");
		await enabled.click();
		await expect(enabled).toBeChecked();
		await save.click();
		await expect(async () => expect(await stored()).toMatchObject({ desktopWeb: { enabled: true, host: "::1", port: 19200 } })).toPass();
		await selectSettingsCategory(page, "会话行为");
		const compaction = settings.getByRole("checkbox", { name: "自动压缩", exact: true });
		const initialCompaction = await compaction.isChecked();
		const sessionFile = path.join(agentDir, "settings.json");
		const originalSession = await readFile(sessionFile, "utf8");
		await compaction.click();
		expect(await readFile(sessionFile, "utf8")).toBe(originalSession);
		await discard.click();
		await expect(compaction).toBeChecked({ checked: initialCompaction });
		await compaction.click();
		await save.click();
		await expect(async () => expect(parse(await readFile(sessionFile, "utf8"))).toMatchObject({ compaction: { enabled: !initialCompaction } })).toPass();
		await expect(save).toBeDisabled();
		await settings.getByRole("button", { name: "关闭面板", exact: true }).click();
		await expect(settings).not.toBeVisible();
		await page.reload();
		const editor = page.getByRole("textbox", { name: "消息", exact: true });
		await editor.fill("/name 快捷键验证");
		await editor.press("Enter");
		await expect(page.locator(".topbar .session-name")).toHaveText("快捷键验证");
		await open();
		const external = { ...parse(await readFile(file, "utf8")), theme: "light" };
		await writeFile(file, JSON.stringify(external));
		await selectSetting(page, "主题", "跟随系统");
		await save.click();
		expect(await stored()).toEqual(external);
		await discard.click();
		await settings.getByRole("button", { name: "重新读取", exact: true }).click();
		await selectSettingsCategory(page, "子代理");
		const parallel = settings.getByRole("spinbutton", { name: "最大并行任务数", exact: true });
		await parallel.fill("6");
		await selectSettingsCategory(page, "自动标题");
		await selectSettingsCategory(page, "子代理");
		await expect(parallel).toHaveValue("6");
		await settings.getByRole("button", { name: "关闭面板", exact: true }).click();
		await page.getByRole("button", { name: "继续编辑", exact: true }).click();
		await settings.getByRole("button", { name: "保存", exact: true }).click();
		const moduleFile = path.join(agentDir, "configs", "subagent.jsonc");
		await expect(async () => expect(parse(await readFile(moduleFile, "utf8"))).toMatchObject({ max_parallel_tasks: 6 })).toPass();
		await expect(settings.getByRole("button", { name: "保存", exact: true })).toBeDisabled();
		await writeFile(moduleFile, '{"max_parallel_tasks":3}');
		await parallel.fill("8");
		await settings.getByRole("button", { name: "保存", exact: true }).click();
		await expect(parallel).toHaveValue("8");
		expect(parse(await readFile(moduleFile, "utf8"))).toEqual({ max_parallel_tasks: 3 });
		await settings.getByRole("button", { name: "放弃修改", exact: true }).click();
	});
});
