import { Theme } from "@earendil-works/pi-coding-agent";

/** SDK 绑定 UI 时会读取 Theme。空色值保留文本，不创建终端组件。 */
export const plainTheme = new Theme(
	{
		accent: "",
		border: "",
		borderAccent: "",
		borderMuted: "",
		success: "",
		error: "",
		warning: "",
		muted: "",
		dim: "",
		text: "",
		thinkingText: "",
		userMessageText: "",
		customMessageText: "",
		customMessageLabel: "",
		toolTitle: "",
		toolOutput: "",
		mdHeading: "",
		mdLink: "",
		mdLinkUrl: "",
		mdCode: "",
		mdCodeBlock: "",
		mdCodeBlockBorder: "",
		mdQuote: "",
		mdQuoteBorder: "",
		mdHr: "",
		mdListBullet: "",
		toolDiffAdded: "",
		toolDiffRemoved: "",
		toolDiffContext: "",
		syntaxComment: "",
		syntaxKeyword: "",
		syntaxFunction: "",
		syntaxVariable: "",
		syntaxString: "",
		syntaxNumber: "",
		syntaxType: "",
		syntaxOperator: "",
		syntaxPunctuation: "",
		thinkingOff: "",
		thinkingMinimal: "",
		thinkingLow: "",
		thinkingMedium: "",
		thinkingHigh: "",
		thinkingXhigh: "",
		bashMode: "",
	},
	{ selectedBg: "", userMessageBg: "", customMessageBg: "", toolPendingBg: "", toolSuccessBg: "", toolErrorBg: "" },
	"truecolor",
);
